# Generated by Django 4.2.9 on 2025-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_pdf_file_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='targeted_search_engine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
