# Generated by Django 4.2.9 on 2025-08-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsnapshot',
            name='search_engine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ranking.searchengine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='name',
            field=models.CharField(choices=[('Google', 'Google'), ('Google Mobile', 'Google Mobile'), ('Bing', 'Bing'), ('Yahoo', 'Yahoo')], max_length=100),
        ),
    ]
